language: php
php:
  - '5.6'

services:
  - docker

before_script:
  - composer install

script: 
  - vendor/bin/phpcs -s --colors --standard=./vendor/magento-ecg/coding-standard/Ecg app/
  - vendor/bin/phpmd app/ text codesize
  - vendor/bin/phpcpd app/
  - vendor/bin/phpdoccheck --directory=app
  - vendor/bin/phploc app/
  - vendor/bin/phpunit --bootstrap dev/tests/bootstrap.php dev/tests/unit/
  - docker build -t bliskapaczkapl/magento .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push bliskapaczkapl/magento;
    fi