version: "3"
services:
  magento:
    image: bliskapaczkapl/magento:7.2_1.9.4.0
    depends_on:
      - db
    ports:
      - "8080:80"
    env_file:
      - ./dev/docker/mysql/env
    environment:
      DB_HOST: db
    depends_on:
      - db
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    env_file:
     - ./dev/docker/mysql/env
